server:
  #port: 8443
  port: 9090
  context-path: /boot
  session:
    timeout: 3600
  tomcat:
    uri-encoding: utf-8
#  SSL配置
#  ssl:
#    key-store: debug.keystore
#    key-password: 311311
#    key-store-type: JKS
#    key-alias: androiddebugkey