package com.fnic.mybatis.dao;

import com.fnic.mybatis.model.AttributeKv;
import com.fnic.mybatis.model.AttributeKvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeKvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    long countByExample(AttributeKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    int deleteByExample(AttributeKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    int insert(AttributeKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    int insertSelective(AttributeKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    List<AttributeKv> selectByExample(AttributeKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AttributeKv record, @Param("example") AttributeKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AttributeKv record, @Param("example") AttributeKvExample example);
}